### ISSUE TITLE
Upload Clips

### ISSUE THREAD

**Issue by tonybaloney72** [tonybaloney72/TwitchClone#3]
# Upload Clips

### Functionality

- [x] Users must be logged in to upload videos
- [x] Users cannot access link to upload ('/upload') videos if they are not logged in
- [x] Users must be logged in to delete videos
- [x] Users cannot delete videos they did not upload
- [x] Users can add details through the submit form for the clip such as the title and category
- [x] Users are redirected to home page after successfully deleting a clip

## Style

- [x] There is a video preview of the selected clip you are uploading
- [x] The form and buttons are in-line with the rest of the website

## Seeds

- [x] There are adequate and appropriate seeds

**Comment by jenvomo** [comment]
Nice job @tonybaloney72 ! Only thing to note is that I am able to fire off an ajax call from the console of your app to delete a clip when I am not logged in, and successfully delete the clip.  You might want to add a cb to your controller to ensure logged in for specific controller actions so they don't allow someone to delete something if they aren't actually logged in

**Comment by jenvomo** [comment]
- [ ] Add owner info to clip show page (channel name, channel image or stock icon)
